### PR TITLE
Fix 'graphiql-subscriptions-fetcher' import

### LINKED ISSUE #24: Can't resolve 'graphiql-subscriptions-fetcher'
I'm trying to build [graphiql-workspace-app](https://gitlab.com/kachkaev/graphiql-workspace-app) after updating to 1.0.5 and am getting this error:

```
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve 'graphiql-subscriptions-fetcher' in '/path/to/graphiql-workspace-app/node_modules/graphiql-workspace/dist'
```

@tlvenn could this be related to your [changes in package.json](https://github.com/OlegIlyenko/graphiql-workspace/blame/master/package.json#L27-L29)?

__UPD:__ See [CI build logs](https://gitlab.com/kachkaev/graphiql-workspace-app/-/jobs/34422226).

### PR DESCRIPTION
**Pull request by kachkaev**
Closes #24
Reason: https://github.com/apollographql/GraphiQL-Subscriptions-Fetcher/issues/4

cc @tlvenn

### CODE REVIEW

**Comment by OlegIlyenko** [comment]
👍

**Comment by kachkaev** [comment]
Thanks @OlegIlyenko! I tried building [graphiql-workspace-app](https://gitlab.com/kachkaev/graphiql-workspace-app) with `npm link` and it worked! Would be great if you could release `1.1.0` so that I could officially update the docker image via GitLab CI.

**Comment by OlegIlyenko** [comment]
Awesome, just give me a sec! Also good point about the version number 👍

**Comment by OlegIlyenko** [comment]
published https://github.com/OlegIlyenko/graphiql-workspace/releases/tag/v1.1.0

**Comment by kachkaev** [comment]
Yay! It worked. Thank you for releasing 1.1.0 @OlegIlyenko!

**Pull request merged**
